server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=library_db;encrypt=true;trustServerCertificate=true
    username: sa
    password: 1234567890
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

  application:
    name: library-management    

  jackson:
    time-zone: Asia/Bangkok

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect

jwt:
  signerKey: "60M5CCxTcS4Hm6qLkNCcGvP1WmZ0ffbmDCIdyDDNkVL32fvZSndndfM5vWfSgEgk"
  valid-duration: 3600
  refreshable-duration: 36000

debug: true
